package android.pownpon.appmodel.bean

data class GoodsBean(
    val AutoId: Int,
    val AucId: String,
    val SellerId: String,
    val Seller: String,
    val AucType: Int,
    val AucClassId: Int,
    val ShopClassId: Int,
    val AucTitle: String,
    val StartTime: String,
    val EndTime: String,
    val AucNum: Int,
    val AucSpec: String,
    val AucPro: String,
    val AucCity: String,
    val StartPrice: Float,
    val ExtPrice: Float,
    val ImmPrice: Float,
    val AucHot: Int,
    val TraPayMethod: Int,
    val TraObject: Int,
    val ChTraPrice: Float,
    val DeTraPrice: Float,
    val EmsTraPrice: Float,
    val AucIP: String,
    val AucIsdel: Int,
    val AucIsSell: Int,
    val AucGoodsType: Int,
    val AucIsEvacuate: Int,
    val AucIsPay: Int,
    val AucIsOrchid: Int,
    val BigSrc: String,
    val MidSrc: String,
    val SmallSrc: String,
    val TopPrice: Float,
    val PriceNum: Int,
    val UserRate: Int,
    val ExId: Int,
    val AucHits: Int,
    val GreatTime: String,
    val TopUserId: String,
    val IsReturnSer: Int,
    val AucIsRepeat: Int,
    val OrchidBigSort: Int,
    val OrchidFloSort: Int,
    val CancelTransNums: Int,
    val ClassTitle: String,
    // 是否是手机上传，0不是，1是
    val IsPhonePub: Int,
    //  1 在直播，0 不在直播
    val IsLive: Int,
    val IsBusiness: String,
    val UserRegtime: String,
    val UserSellerRateTotal: Int,
    val UserIsSeller: Int,
    val UserSellerType: Int,
    //直播数据，非数据库字段
    //ViewLiving LiveData :String,
)
